ben_doctors_ben_availability:
    resource: "@BenDoctorsBundle/Resources/config/routing/availability.yml"
    prefix:   /ben_availability

ben_doctors_ben_appointment:
    resource: "@BenDoctorsBundle/Resources/config/routing/appointment.yml"
    prefix:   /ben_appointment


ben_doctors_default:
    resource: "@BenDoctorsBundle/Resources/config/routing/default.yml"

ben_doctors_person:
    resource: "@BenDoctorsBundle/Resources/config/routing/person.yml"
    prefix:   /person

ben_doctors_test:
    resource: "@BenDoctorsBundle/Resources/config/routing/test.yml"
    prefix:   /examen

ben_doctors_meds:
    resource: "@BenDoctorsBundle/Resources/config/routing/meds.yml"
    prefix:   /medicaments

ben_doctors_consultation:
    resource: "@BenDoctorsBundle/Resources/config/routing/consultation.yml"
    prefix:   /consultation

ben_doctors_antecedent:
    resource: "@BenDoctorsBundle/Resources/config/routing/antecedent.yml"
    prefix:   /antecedent

ben_doctors_config:
    resource: "@BenDoctorsBundle/Resources/config/routing/config.yml"
    prefix:   /config
link_to:
    pattern:  /link
    defaults: { _controller: BenDoctorsBundle:Person:link }
distant_access:
    path: /auth/{name}/{id}
    defaults: { _controller:"BenDoctorsBundle:Utility:authenticate" }
    requirements: { _method: get }

ben_doctors_calendar:
    path: /calendar
    defaults: { _controller:"BenDoctorsBundle:Calendar:index" }
    requirements: { _method: get }

#distant_log
ben_log_user:
  path:       /log/{name}
  defaults:    {_controller: "BenDoctorsBundle:Utility:prepareLogin"}
  requirements: { _method: get }

#trial FineUplaader
ben_fine_upload:
  path:       /fine_upload
  defaults:    {_controller: "BenDoctorsBundle:Utility:fineUpload"}
  requirements: { _method: get }
#trial
ben_trial:
  path:       /trial/{int}
  defaults:    {_controller: "BenDoctorsBundle:Default:trial"}
  requirements: {_method: get}
#file upload
ben_file_upload:
  path:       /upload
  defaults:   {_controller: "BenDoctorsBundle:Default:upload"}
  requirements: {_method: get}