ben_appointment:
    path:     /
    defaults: { _controller: "BenDoctorsBundle:Appointment:index" }

ben_appointment_show:
    path:     /{id}/show
    defaults: { _controller: "BenDoctorsBundle:Appointment:show" }



ben_appointment_create:
    path:     /create/{date}/{person}
    defaults: { _controller: "BenDoctorsBundle:Appointment:create" }
    methods:  POST|GET



ben_appointment_update:
    path:     /{id}/update/{date}/{person}
    defaults: { _controller: "BenDoctorsBundle:Appointment:update",date:null }
    methods:  [POST, PUT]

ben_appointment_delete:
    path:     /{id}/delete
    defaults: { _controller: "BenDoctorsBundle:Appointment:delete" }
    methods:  [POST, DELETE]
take_appointment:
    path:     /take_appointment/{date}/{person}
    defaults:  { _controller: "BenDoctorsBundle:Appointment:takeAppointment" }
    methods: POST