ben_dashboard:
    pattern:  /
    defaults: { _controller: BenDoctorsBundle:Default:index }

ben_stats:
    pattern:  /stats
    defaults: { _controller: BenDoctorsBundle:Default:stats }
ben_chart_api:
    pattern: /chart
    defaults: {_controller: BenDoctorsBundle:Default:chartApi}
ben_top_chart_api:
    pattern: /top_chart
    defaults: {_controller: BenDoctorsBundle:Default:topChartApi}